### ISSUE TITLE
using uart1 instead of USB

### ISSUE THREAD

**Issue by mafekam314** [NXPmicro/sbl#2]
Hello,

So I compiled the sbl boot and burned the image on flash, but I discovered that the uart1 on demo board is only for debug.
and the usb is used for boot communications.
However I don't need the debug on uart I need it for loading the image.
from the documentations it say that sbl support usb and uart so how I can unblock uart1 as communication channel ?
please help ?

**Comment by Tim-Wang38** [comment]
>Hi, 
When the sbl start to run, it will wait few seconds to let you run into ISP mode, in this mode, you can load your image into the flash. The specific operation please refer to the chapter7.2.1 of the UG.

**Comment by mafekam314** [comment]
ok thank you my bad.
I tried now and I was able to connect to both usb and uart.
Yesterday I tried to connect to uart but I had no luck only with usb but maybe I had a problem with uart settings
anyway thanks for fast response.
